version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    working_dir: /var/www/html
    tty: true
    ports:
      - 8090:80
    volumes:
      - ./:/var/www/html
